# my_statement_blocker/Makefile
EXTENSION = block_unsupported
DATA = block_unsupported--1.0.sql
MODULES = block_unsupported

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
